### ISSUE TITLE
proc_hard sysctl return code 255 issue

### ISSUE THREAD

**Issue by cpoma** [USGS-CIDA/stig#121]
The guard that was added in the PR #116 doesn't seem to be working. If I add my suggested code to proc_hard it seems to work. After adding the fix (return [0,255]) so the code can run the Chef run, the idempotent run stuff has disappeared in this build.

```ruby
node['sysctl']['params'].each do |param, value|
  sysctl_param param do
    key param
    value value
    only_if "sysctl -n -e #{param}"
    return [0,255]
  end
end
```
**ERROR OUTPUT**
```bash
Recipe: stig::proc_hard
  * template[/etc/security/limits.conf] action create (up to date)
  * yum_package[apport] action remove (skipped due to only_if)
  * yum_package[whoopsie] action remove (skipped due to only_if)
  * sysctl_param[fs.suid_dumpable] action apply (up to date)
  * sysctl_param[net.ipv4.ip_forward] action apply (up to date)
  * sysctl_param[net.ipv4.conf.all.send_redirects] action apply (up to date)
  * sysctl_param[net.ipv4.conf.default.send_redirects] action apply (up to date)
  * sysctl_param[net.ipv4.conf.all.accept_redirects] action apply (up to date)
  * sysctl_param[net.ipv4.conf.default.accept_redirects] action apply (up to date)
  * sysctl_param[net.ipv4.conf.all.log_martians] action apply (up to date)
  * sysctl_param[net.ipv4.conf.default.log_martians] action apply (up to date)
  * sysctl_param[net.ipv4.conf.all.rp_filter] action apply (up to date)
  * sysctl_param[net.ipv4.conf.default.rp_filter] action apply (up to date)
  * sysctl_param[net.ipv6.conf.all.accept_redirects] action apply

    ================================================================================
    Error executing action `apply` on resource 'sysctl_param[net.ipv6.conf.all.accept_redirects]'
    ================================================================================

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '255'
    ---- Begin output of sysctl -w "net.ipv6.conf.all.accept_redirects=0" ----
    STDOUT:
    STDERR: sysctl: cannot stat /proc/sys/net/ipv6/conf/all/accept_redirects: No such file or directory
    ---- End output of sysctl -w "net.ipv6.conf.all.accept_redirects=0" ----
    Ran sysctl -w "net.ipv6.conf.all.accept_redirects=0" returned 255

    Cookbook Trace:
    ---------------
    /var/chef/cache/cookbooks/sysctl/resources/param.rb:98:in `set_sysctl_param'
    /var/chef/cache/cookbooks/sysctl/resources/param.rb:55:in `block (2 levels) in class_from_file'
    /var/chef/cache/cookbooks/sysctl/resources/param.rb:53:in `block in class_from_file'

    Resource Declaration:
    ---------------------
    # In /var/chef/cache/cookbooks/stig/recipes/proc_hard.rb

     26:   sysctl_param param do
     27:     key param
     28:     value value
     29:     only_if "sysctl -n -e #{param}"
     30:   end
     31: end

    Compiled Resource:
    ------------------
    # Declared in /var/chef/cache/cookbooks/stig/recipes/proc_hard.rb:26:in `block in from_file'

    sysctl_param("net.ipv6.conf.all.accept_redirects") do
      action [:apply]
      default_guard_interpreter :default
      declared_type :sysctl_param
      cookbook_name "stig"
      recipe_name "proc_hard"
      key "net.ipv6.conf.all.accept_redirects"
      value "0"
      only_if "sysctl -n -e net.ipv6.conf.all.accept_redirects"
    end

    System Info:
    ------------
    chef_version=13.6.4
    platform=redhat
    platform_version=7.4
    ruby=ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
    program_name=chef-client worker: ppid=17005;start=09:45:54;
    executable=/opt/chefdk/bin/chef-client


Running handlers:
[2018-04-27T09:46:01-04:00] ERROR: Running exception handlers
Running handlers complete
[2018-04-27T09:46:01-04:00] ERROR: Exception handlers complete
Chef Client failed. 0 resources updated in 06 seconds
[2018-04-27T09:46:01-04:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
[2018-04-27T09:46:01-04:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-04-27T09:46:01-04:00] ERROR: sysctl_param[net.ipv6.conf.all.accept_redirects] (stig::proc_hard line 26) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '255'
---- Begin output of sysctl -w "net.ipv6.conf.all.accept_redirects=0" ----
STDOUT:
STDERR: sysctl: cannot stat /proc/sys/net/ipv6/conf/all/accept_redirects: No such file or directory
---- End output of sysctl -w "net.ipv6.conf.all.accept_redirects=0" ----
Ran sysctl -w "net.ipv6.conf.all.accept_redirects=0" returned 255
[2018-04-27T09:46:01-04:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by isuftin** [comment]
@cpoma What's the exit code on your live system from `sysctl -n -e net.ipv6.conf.all.accept_redirects` ?

If it's non-0, that block should never run due to the only_if guard... ?

**Comment by cpoma** [comment]
@isuftin Oddly... it's 0 from bash. But in the Chef run it seems to be 255?
```bash 
[root@chefcomplianceserver tmp]# echo $0
bash
[root@chefcomplianceserver tmp]# sysctl -n -e net.ipv6.conf.all.accept_redirects
[root@chefcomplianceserver tmp]# echo $?
0
```

**Comment by isuftin** [comment]
Yeesh. 

What about if you remove the `-e` flag from that check?

`sysctl -n net.ipv6.conf.all.accept_redirects`

I think I should not have added the `-e` flag in that check since that's specifically to ignore any errors

**Comment by cpoma** [comment]
@isuftin - That gets us a 255 error :-)

```bash

[root@chefcomplianceserver tmp]# sysctl -n net.ipv6.conf.all.accept_redirects
sysctl: cannot stat /proc/sys/net/ipv6/conf/all/accept_redirects: No such file or directory
[root@chefcomplianceserver tmp]# echo $?
255
```

**Comment by isuftin** [comment]
@cpoma Alright I'll make the update to the codebase for this.

**Comment by isuftin** [comment]
Waiting for Travis build on PR https://github.com/USGS-CIDA/stig/pull/123
